- net/_index.md
- net/developer-guide/presentation-content/manage-ole/_index.md
The article has been corrected according to the solved task SLIDESNET-42314.
> Article on working with OLE-objects has been corrected.

- net/_index.md
- net/developer-guide/presentation-content/manage-ole/_index.md
* Article on working with OLE-objects has been corrected.
* OLE-objects article minor changes, snippets updated
* Anchor links to corresponding sections have been added.
* net: markup fixes for ole article and main page;
Co-authored-by: Serhii Puchok <Serhii.Puchok@aspose.com>
Co-authored-by: yury-knml <61190469+yury-knml@users.noreply.github.com>
Co-authored-by: Alexandra <alexandra.grazhevskaja@aspose.com>
> Article on working with OLE-objects has been corrected. (#9)

- cpp/developer-guide/technical-articles/extracting-images-from-presentation-shapes/_index.md
[SLIDESCPP-2729](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-2729)
> Added "Extracting Images from Presentation shapes" article for С++

- java/developer-guide/programming-with-slides/manage OLE/_index.md
- java/developer-guide/programming-with-slides/managing-header-and-footers/_index.md
- java/developer-guide/programming-with-slides/removing-slide-notes-and-add-notesstyle/_index.md
- java/developer-guide/programming-with-slides/rendering-a-slide/_index.md
- java/developer-guide/programming-with-slides/slide-transitions/_index.md
- java/developer-guide/programming-with-slides/working-with-charts/_index.md
- java/developer-guide/programming-with-slides/working-with-comments/_index.md
- java/developer-guide/programming-with-slides/working-with-shapes/_index.md
Added the article about managing OLE objects
> Added the article about managing OLE objects

- cpp/developer-guide/programming-with-presentation/adding-formatting-and-manipulating-slides/convert-slide/_index.md
[SLIDESCPP-2761](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-2761)
> cpp: Added the article on converting a slide to an image.

- cpp/developer-guide/technical-articles/copy-paragraph-and-portion-in-pptx/_index.md
- cpp/developer-guide/technical-articles/copying-paragraph-and-portion-in-pptx/_index.md
[SLIDESCPP-2748](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-2748)
> cpp: Updated the "Copying Paragraph and Portion in PPTX" article

- jasperreports/release-notes/release-notes-2021/aspose-slides-for-jasper-reports-21-2-release-notes/_index.md
- java/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2021/aspose-slides-for-android-via-java-21-2-release-notes/_index.md
- java/release-notes/aspose-slides-for-java/release-notes-2021/aspose-slides-for-java-21-2-release-notes/_index.md
Aspose.Slides for Java/JasperReports/Android via Java 21.2 Release Notes
> Aspose.Slides for Java/JasperReports/Android via Java 21.2 Release Notes

- cpp/release-notes/release-notes-2021/aspose-slides-for-cpp-21-3-release-notes/_index.md
Aspose.Slides for C++ 21.3 Release Notes
> Aspose.Slides for C++ 21.3 Release Notes

- jasperreports/release-notes/release-notes-2021/aspose-slides-for-jasper-reports-21-3-release-notes/_index.md
- java/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2021/aspose-slides-for-android-via-java-21-3-release-notes/_index.md
- java/release-notes/aspose-slides-for-java/release-notes-2021/aspose-slides-for-java-21-3-release-notes/_index.md
Aspose.Slides for Java/JasperReports/Android via Java 21.3 Release Notes
> Aspose.Slides for Java/JasperReports/Android via Java 21.3 Release Notes

- java/developer-guide/presentation-design/powerpoint-fonts/custom-font/_index.md
Java: Article custom-font has been improved.
> Java: Article custom-font has been improved.

- cpp/developer-guide/presentation-design/powerpoint-fonts/custom-font/_index.md
[SLIDESCPP-2859](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-2859)
> cpp: The "Custom Font" article was updated.

- cpp/developer-guide/presentation-content/manage-ole/_index.md
[SLIDESCPP-2730](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-2730)
> cpp: Updating the article on managing OLE objects.

- cpp/developer-guide/presentation-content/powerpoint-shapes/shape-manipulations/_index.md
[SLIDESCPP-2838](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-2838)
> cpp: Added the "Shapes Alignment" point to the "Shape Manipulation" 

- cpp/release-notes/release-notes-2021/aspose-slides-for-cpp-21-4-release-notes/_index.md
Aspose.Slides for C++ 21.4 Release Notes
> Aspose.Slides for C++ 21.4 Release Notes

- java/developer-guide/presentation-content/manage ole/_index.md
SLIDESJAVA-38461 Article manage-ole has been improved.
> SLIDESJAVA-38461 Article manage-ole has been improved.

- java/developer-guide/presentation-content/powerpoint-shapes/shape-manipulations/_index.md
SLIDESJAVA-38468 Article shape-manipulation has been improved.
> SLIDESJAVA-38468 Article shape-manipulation has been improved.

- jasperreports/release-notes/release-notes-2021/aspose-slides-for-jasper-reports-21-4-release-notes/_index.md
- java/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2021/aspose-slides-for-android-via-java-21-4-release-notes/_index.md
- java/release-notes/aspose-slides-for-java/release-notes-2021/aspose-slides-for-java-21-4-release-notes/_index.md
Aspose.Slides for Java/JasperReports/Android via Java 21.4 Release Notes
> Aspose.Slides for Java/JasperReports/Android via Java 21.4 Release Notes

- net/developer-guide/presentation-content/powerpoint-charts/create-chart/_index.md
I rewrote some sentences, corrected most errors, and improved the structure. I did not touch the main topic (Create Charts) to avoid breaking links stored by users. In the future, the main topic should read "Creating charts".
I added a subtopic  (Creating Fusion Charts) based on
<table><tbody><tr><td>SLIDESNET-16733</td><td>Fusion Charts support in Aspose.Slides</td><td>Feature</td></tr></tbody></table>
 I'll need more information to write the steps.
> SLIDESDOC-1: Creating Fusion Charts

- net/developer-guide/presentation-content/powerpoint-charts/create-chart/_index.md
Reverts aspose-slides/Aspose.Slides-Documentation#51
> Revert "SLIDESDOC-1: Creating Fusion Charts"

- net/developer-guide/presentation-content/powerpoint-charts/create-chart/_index.md
I added a subtopic (Creating Fusion Charts) based on 
SLIDESNET-16733 | Fusion Charts support in Aspose.Slides | Feature
-- | -- | --
I also corrected errors and improved the article's structure.
> Creating Fusion Charts and some edits

- net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-ppt-and-pptx-to-pdf/_index.md
I added a new section (How to Convert PPT to PDF online) and made several changes to correct errors. I wanted to improve the article for SEO based on the SLIDESDOC-20 task.
> Rewrote the Convert PowerPoint PPT and PPTX to PDF page

- net/developer-guide/presentation-content/manage-ole/_index.md
I updated the "Manage OLE" article to add new these sections: "Embedding Other File Types in Slides" and
"Extracting Embedded Files".
I also rewrote certain parts of other sections and corrected errors (as usual).
If you have questions, suggestions, or useful explanations, please write me.
> SLIDESDOC17--Embedding html and zip files--Manage OLE

- net/developer-guide/presentation-content/manage-text/animated-text/_index.md
I made changes to the topic to correct errors and explained things better. The topic should be easier to find now.
> SLIDESDOC-16--Improvements for "Animated text" topic

- cpp/getting-started/how-to-run-aspose-slides-cpp-in-docker/_index.md
[SLIDESCPP-2897](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-2897)
> Added an article about using Aspose.Slides for C++ in Docker

- net/developer-guide/presentation-security/password-protected-presentation/_index.md
I initially wanted to mention something about support for ODP and OTP formats, but I ended up rewriting the entire article.
I did some research, held discussions with the right people, combined elements from the Java and C++ versions of the article, and so on.
> Rewrote the "Password Protected..." article

- cpp/developer-guide/technical-articles/replacing-images-inside-presentation-image-collection/_index.md
Updated the "Replacing Images inside Presentation Image Collection" article.
[SLIDESCPP-2752](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-2572)
> SLIDESCPP-2752 

- cpp/developer-guide/knowledge-base/_index.md
- cpp/developer-guide/knowledge-base/multithreading/_index.md
[SLIDESCPP-2920](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-2920)
> SLIDESCPP-2920 Added the "Multithreading in Aspose.Slides" article.

- java/developer-guide/knowledge-base/multithreading/_index.md
Added the "Multithreading in Aspose.Slides" article
> SLIDESJAVA-38534 Added the "Multithreading in Aspose.Slides" article.

- net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-ppt-and-pptx-to-pdf/_index.md
Added info for PDF/A1a, PDF/A1b, and PDF/UA compliance and accessibility standards... for these tasks: SLIDESDOC-27, SLIDESDOC-30, SLIDESDOC-31, and SLIDESDOC-36
> Slidesdoc 27,30,31,36  pdf/ua compliance/access

- cpp/developer-guide/technical-articles/exporting-presentations-to-html-with-externally-linked-images/_index.md
Updated the "Exporting Presentations to HTML with Externally Linked Images" article.
[SLIDESCPP-2750](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-2750)
> SLIDESCPP-2750 

- net/developer-guide/presentation-content/powerpoint-math-equations/exporting-math-equations/_index.md
Added a new topic, description, and code sample.
> SLIDESDOC-32: Added a new section/article -- Export to MathML (and mentioned LaTeX)

- java/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-ppt-and-pptx-to-doc-and-docx/_index.md
- net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-ppt-and-pptx-to-doc-and-docx/_index.md
For.NET, I rewrote the article, added a backlink, and added a code sample. 
For Java, I simply added a backlink. We can leave the Java article as it is. It does NOT have to mirror the .NET version.
> Backlinks: Slidesapp 615 -- Improving the PPT to Word page

- cpp/developer-guide/technical-articles/re-sizing-shapes-on-slide/_index.md
[SLIDESCPP-2753](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-2753)
> Updated the "Re-sizing Shapes on Slide" article

- cpp/developer-guide/technical-articles/support-for-interruptable-library/_index.md
[SLIDESCPP-2746](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-2746)
> Added the "Support For Interruptable Library" article.

- net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/render-a-slide-as-an-svg-image/_index.md
- net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/render-slide-as-svg-image/_index.md
- net/plugins/aspose-slides-for-openxml/missing-features-in-openxml/rendering-and-printing-of-presentation/render-slide-as-svg-image/_index.md
I rewrote the article from scratch, added the new code sample Yura provided, deleted the image that was no longer showing, deleted the "Download Sample Code" section (because I changed the sample code), moved the article to a better location, and so on. 
I still left a copy of the article in the original (wrong) location... in case we have readers that still go there (or to avoid breaking old links).
> SLIDESDOC-42--Changes for the SVG article

- cpp/developer-guide/technical-articles/working-solution-for-chart-resizing-in-pptx/_index.md
[SLIDESCPP-2747](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-2747)
> Added the "Working Solution for Chart Resizing in PPTX" article.

- java/developer-guide/presentation-content/powerpoint-shapes/shape-types/image/_index.md
Minor fixes in shape-types-image article
> Minor fixes in shape-types-image article

- cpp/developer-guide/presentation-content/managing-tags-and-custom-data/_index.md
[SLIDESCPP-2982](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-2982)
> CPP: Added "Managing Tags and Custom Data" article

- net/developer-guide/presentation-slide/slide-master/_index.md
- net/developer-guide/presentation-slide/slide-section/_index.md
- net/developer-guide/presentation-slide/slide-size/_index.md
- net/developer-guide/presentation-slide/slide-transition/_index.md
I wrote the article and made some changes to alter the order of the articles in this section.
> Added the Slide Size article

- net/developer-guide/presentation-slide/slide-section/_index.md
I improved the article and added new details based on my research for the SLIDESDOC-43 task.
> Rewrote the "Section" article

- androidjava/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2021/aspose-slides-for-android-via-java-21-6-release-notes/_index.md
- jasperreports/release-notes/release-notes-2021/aspose-slides-for-jasper-reports-21-6-release-notes/_index.md
- java/release-notes/aspose-slides-for-java/release-notes-2021/aspose-slides-for-java-21-6-release-notes/_index.md
Aspose.Slides for Java/JasperReports/Android via Java 21.6 Release Notes
> Aspose.Slides for Java/JasperReports/Android via Java 21.6 Release Notes

- androidjava/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2021/aspose-slides-for-android-via-java-21-6-release-notes/_index.md
- jasperreports/release-notes/release-notes-2021/aspose-slides-for-jasper-reports-21-6-release-notes/_index.md
- java/release-notes/aspose-slides-for-java/release-notes-2021/aspose-slides-for-java-21-6-release-notes/_index.md
> Slides java 2021/aspose slides 21 6 release notes

- java/developer-guide/presentation-content/managing-tags-and-custom-data/_index.md
Added Managing Tags and Custom Data article
> SLIDESJAVA-38554 JAVA: Added Managing Tags and Custom Data

- java/developer-guide/presentation-slide/slide-section/_index.md
> SLIDESJAVA-38557 Rewrote the "Section" article

- java/developer-guide/presentation-security/read-only-presentatiom/_index.md
JAVA: "Read-only recommended" Article
> JAVA: "Read-only recommended" Article

- cpp/developer-guide/presentation-security/read-only-presentatiom/_index.md
[SLIDESCPP-2984](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-2984)
> CPP: Added the "Read-only recommended" article.

- cpp/developer-guide/presentation-slide/slide-section/_index.md
[SLIDESCPP-2983](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-2983)
> CPP: Rewrote the Section article

- cpp/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-ppt-and-pptx-to-pdf-with-notes/_index.md
[SLIDESCPP-3016](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3016)
> SLIDESCPP-3016: Added "Convert PowerPoint PPT and PPTX to PDF with Notes" article 

- cpp/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-ppt-and-pptx-to-tiff-with-notes/_index.md
[SLIDESCPP-3017](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3017)
> SLIDESCPP-3017: Added "Convert PowerPoint PPT and PPTX to TIFF with Notes" article

- cpp/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-ppt-and-pptx-to-doc-and-docx/_index.md
- cpp/developer-guide/presentation-content/manage-text/extract-text-from-presentation/_index.md
Also added the "Extract Text from Presentation" article.
[SLIDESCPP-3018](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3018)
> SLIDESCPP-3018: Added "Convert PowerPoint PPT and PPTX to DOC and DOCX" article

- cpp/developer-guide/manage-presentation/open-presentation/_index.md
[SLIDESCPP-3020](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3020)
> SLIDESCPP-3020 Updated "Open Presentation" article

- cpp/developer-guide/presentation-slide/convert-slide/_index.md
[SLIDESCPP-3022](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3022)
> SLIDESCPP-3022 Updated "Convert Slide" article

- cpp/developer-guide/presentation-content/manage-text/manage-textbox/_index.md
[SLIDESCPP-3025](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3025)
> SLIDESCPP-3025 Updated "Manage TextBox" article.

- cpp/developer-guide/presentation-slide/slide-transition/_index.md
[SLIDESCPP-3023](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3023)
> SLIDESCPP-3023 Updated "Slide Transition" article

- cpp/developer-guide/presentation-content/manage-text/text-formatting/_index.md
[SLIDESCPP-3026](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3026)
> SLIDESCPP-3026 Updated "Text Formatting" article

- androidjava/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2021/aspose-slides-for-android-via-java-21-7-release-notes/_index.md
- jasperreports/release-notes/release-notes-2021/aspose-slides-for-jasper-reports-21-7-release-notes/_index.md
- java/release-notes/aspose-slides-for-java/release-notes-2021/aspose-slides-for-java-21-7-release-notes/_index.md
Aspose.Slides for Java/JasperReports/Android via Java 21.7 Release Notes
> Aspose.Slides for Java/JasperReports/Android via Java 21.7 Release Notes

- net/developer-guide/presentation-content/manage-ole/_index.md
I added a new section and description (Setting Icon Images and Titles for Embedded Objects) based on a request.
> SLIDESDOC-65: Improve "Manage OLE" article

- net/developer-guide/presentation-content/manage-text/wordart/_index.md
Rewrote sentences, added a structure, resolved errors, and so on.
This task was based on an article request for C++, so please C++ (@nikolaysaulyak) and Java (@petrtetenko) product teams have to rewrite or update their WordArt articles based on this one. Thanks. 
@yury-knml you might want to check the code samples in this article.
> SLIDESDOC-47: Rewrote and improved the WordArt article.

- java/developer-guide/presentation-slide/slide-size/_index.md
Changing the size of presentation slides article
> SLIDESDOC-25 Changing the size of presentation slides

- net/developer-guide/presentation-content/manage-text/manage-bullet-and-numbered-lists/_index.md
… .NET
Having gone through the Java article (which was recently restored), I wrote a new article for .NET using elements from that article and some details from my research.
> SLIDESDOC-7: Added the "Manage bullet..." article for .NET

- net/developer-guide/manage-presentation/convert-presentation/_index.md
- net/developer-guide/manage-presentation/create-presentation/_index.md
- net/developer-guide/manage-presentation/examine-presentation/_index.md
- net/developer-guide/manage-presentation/merge-presentation/_index.md
- net/developer-guide/manage-presentation/open-presentation/_index.md
- net/developer-guide/manage-presentation/save-presentation/_index.md
I wrote the article and made some changes to the order of sections (under Manage Presentation).
> SLIDESDOC-141: Added the "Examine Presentation" section/article for .NET

- net/developer-guide/presentation-slide/clone-slides/_index.md
I added a small section (available in Java) to .NET.
> SLIDESDOC-142: Add the "Clone at end in specified section" for .NET

- java/developer-guide/presentation-content/manage-text/wordart/_index.md
Rewrite "WordArt" article for Java
> SLIDESJAVA-38577 Rewrite "WordArt" article for Java

- java/developer-guide/presentation-content/manage-ole/_index.md
Improve "Manage OLE" article for Java
> SLIDESJAVA-38578 Improve "Manage OLE" article for Java

- cpp/developer-guide/presentation-content/powerpoint-charts/create-chart/_index.md
[SLIDESCPP-3028](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3028)
> SLIDESCPP-3028 Updated "Create Chart" article

- cpp/developer-guide/presentation-content/powerpoint-charts/chart-types/data-points-of-treemap-and-sunburst-chart/_index.md
[SLIDESCPP-3029](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3029)
> SLIDESCPP-3029 Added "Data Points of Treemap and Sunburst Chart" article

- cpp/developer-guide/presentation-content/powerpoint-charts/chart-entities/chart-data-table/_index.md
[SLIDESCPP-3030](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3030)
> SLIDESCPP-3030 Added "Chart Data Table" article

- cpp/developer-guide/presentation-content/powerpoint-charts/chart-entities/chart-plot-area/_index.md
[SLIDESCPP-3031](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3031)
> SLIDESCPP-3031 Updated "Chart Plot Area" article

- cpp/developer-guide/presentation-content/powerpoint-charts/chart-calculations/_index.md
[SLIDESCPP-3032](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3032)
> SLIDESCPP-3032 Updating "Chart Calculations" article

- cpp/developer-guide/presentation-content/powerpoint-charts/chart-workbook/_index.md
[SLIDESCPP-3033](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3033)
> SLIDESCPP-3033 Updating "Chart Workbook" article

- cpp/developer-guide/presentation-content/powerpoint-shapes/shape-types/audio-frame/_index.md
[SLIDESCPP-3034](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3034)
> SLIDESCPP-3034 Updating "Audio Frame" article

- cpp/developer-guide/presentation-content/powerpoint-shapes/shape-types/flash/_index.md
[SLIDESCPP-3035](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3035)
> SLIDESCPP-3035 Updated "Flash" article

- cpp/developer-guide/presentation-content/powerpoint-shapes/shape-types/paragraph/_index.md
[SLIDESCPP-3036](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3036)
> SLIDESCPP-3036 Updated "Paragraph" article.

- cpp/developer-guide/presentation-content/powerpoint-shapes/shape-types/picture-frame/_index.md
[SLIDESCPP-3037](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3037)
> SLIDESCPP-3037 Updated "Picture Frame" article.

- cpp/developer-guide/presentation-content/powerpoint-shapes/shape-types/portion/_index.md
[SLIDESCPP-3038](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3038)
> SLIDESCPP-3038 Updated "Portion" article

- cpp/developer-guide/presentation-content/powerpoint-shapes/shape-formatting/_index.md
[SLIDESCPP-3039](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3039)
> SLIDESCPP-3039 Updated "Shape Formatting" article

- cpp/developer-guide/presentation-content/powerpoint-shapes/activex/_index.md
[SLIDESCPP-3041](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3041)
> SLIDESCPP-3041 Updated "ActiveX" article

- cpp/developer-guide/presentation-content/powerpoint-smartart/manage-smartart/_index.md
[SLIDESCPP-3042](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3042)
> SLIDESCPP-3042 Updating "Manage SmartArt" article

- cpp/developer-guide/presentation-content/powerpoint-shapes/shape-manipulations/_index.md
[SLIDESCPP-3040](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3040)
> SLIDESCPP-3040 Updated "Shape Manipulations" article

- cpp/developer-guide/presentation-content/powerpoint-table/manage-rows-and-columns/_index.md
[SLIDESCPP-3043](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3043)
> SLIDESCPP-3043 Updated "Manage Rows and Columns" article

- cpp/developer-guide/presentation-content/powerpoint-table/manage-cells/_index.md
[SLIDESCPP-3044](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3044)
> SLIDESCPP-3044 Updated "Manage Cells" article

- cpp/developer-guide/presentation-design/presentation-header-and-footer/_index.md
[SLIDESCPP-3047](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3047)
> SLIDESCPP-3047 Added "Presentation Header and Footer" article

- cpp/developer-guide/presentation-design/presentation-background/_index.md
[SLIDESCPP-3048](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3048)
> SLIDESCPP-3048 Updated "Presentation Background" article

- cpp/developer-guide/presentation-design/powerpoint-fonts/font-replacement/_index.md
[SLIDESCPP-3049](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3049)
> SLIDESCPP-3049 Added "Font Replacement" article

- cpp/developer-guide/presentation-design/powerpoint-fonts/custom-font/_index.md
[SLIDESCPP-3050](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3050)
> SLIDESCPP-3050 Updated "Custom Font" article

- cpp/developer-guide/presentation-design/powerpoint-fonts/embedded-font/_index.md
[SLIDESCPP-3051](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3051)
> SLIDESCPP-3051 Updated "Embedded Font" article

- cpp/developer-guide/presentation-design/powerpoint-fonts/fallback-font/_index.md
- cpp/developer-guide/presentation-design/powerpoint-fonts/fallback-font/create-fallback-font/_index.md
- cpp/developer-guide/presentation-design/powerpoint-fonts/fallback-font/create-fallback-fonts-collection/_index.md
- cpp/developer-guide/presentation-design/powerpoint-fonts/fallback-font/render-presentation-with-fallback-font/_index.md
[SLIDESCPP-3052](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3052)
> SLIDESCPP-3052 Added missing articles to "Fallback Font"

- cpp/developer-guide/presentation-design/powerpoint-fonts/font-substitution/_index.md
[SLIDESCPP-3053](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3053)
> SLIDESCPP-3053 Updated "Font Substitution" article

- cpp/developer-guide/presentation-viewer/presentation-view-properties/_index.md
[SLIDESCPP-3054](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3054)
> SLIDESCPP-3054 Updated "Presentation View Properties" article

- cpp/developer-guide/presentation-properties/_index.md
[SLIDESCPP-3056](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3056)
> SLIDESCPP-3056 Updated "Presentation Properties" article

- cpp/developer-guide/powerpoint-animation/_index.md
[SLIDESCPP-3057](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3057)
> SLIDESCPP-3057 Added "PowerPoint Animation" article

- net/developer-guide/presentation-content/powerpoint-shapes/shape-types/image/_index.md
I rewrote and improved the article.
> SLIDESDOC-6: Image article

- net/developer-guide/presentation-slide/convert-slide/_index.md
Rewrote the article and made corrections.
> SLIDESDOC-160: Rewrite the "Convert Slide" article

- cpp/developer-guide/presentation-slide/slide-size/_index.md
[SLIDESCPP-3059](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3059)
> SLIDESCPP-3059 CPP: Added "Slide Size" article

- cpp/developer-guide/presentation-content/manage-ole/_index.md
[SLIDESCPP-3074](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3074)
> SLIDESCPP-3074 Improved "Manage OLE" for C++

- cpp/developer-guide/presentation-content/powerpoint-shapes/shape-types/image/_index.md
[SLIDESCPP-3086](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3086)
> SLIDESCPP-3086 Rewrote the Image article in C++

- cpp/developer-guide/manage-presentation/convert-presentation/export-to-xaml/_index.md
[SLIDESCPP-3085](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3085)
> SLIDESCPP-3085 CPP:Created "XAML Export" article

- java/developer-guide/manage-presentation/convert-presentation/export-to-xaml/_index.md
JAVA:Create "XAML Export" article
> SLIDESJAVA-38591 JAVA:Create "XAML Export" article

- net/developer-guide/presentation-content/manage-hyperlinks/_index.md
Reverts aspose-slides/Aspose.Slides-Documentation#195
> Revert "SLIDESDOC-121-Improved the "Manage Hyperlinks" article"

- java/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-ppt-and-pptx-to-animated-gif/_index.md
JAVA:Create "GIF Export" article
> JAVA:Create "GIF Export" article

- cpp/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-ppt-and-pptx-to-animated-gif/_index.md
[SLIDESCPP-3098](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3098)
> SLIDESCPP-3098 CPP: Created "GIF Export" article

- net/developer-guide/manage-presentation/convert-presentation/convert-openoffice-odp/_index.md
- net/developer-guide/manage-presentation/convert-presentation/convert-openoffice-odp/convert-odp-to-pptx/_index.md
- net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-ppt-and-pptx-to-animated-gif/_index.md
- net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-ppt-and-pptx-to-doc-and-docx/_index.md
- net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-ppt-and-pptx-to-html/_index.md
- net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-ppt-and-pptx-to-jpg/_index.md
- net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-ppt-and-pptx-to-pdf-with-notes/_index.md
- net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-ppt-and-pptx-to-pdf/_index.md
- net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-ppt-and-pptx-to-swf-flash/_index.md
- net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-ppt-and-pptx-to-tiff/_index.md
- net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-to-xps/_index.md
- net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-ppt-to-pptx/_index.md
- net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/ppt-vs-pptx/_index.md
- net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/render-a-slide-as-an-svg-image/_index.md
- net/developer-guide/manage-presentation/convert-presentation/export-to-xaml/_index.md
- net/developer-guide/manage-presentation/create-presentation/_index.md
- net/developer-guide/manage-presentation/examine-presentation/_index.md
- net/developer-guide/manage-presentation/merge-presentation/_index.md
- net/developer-guide/manage-presentation/open-presentation/_index.md
- net/developer-guide/manage-presentation/print-presentation/_index.md
- net/developer-guide/manage-presentation/save-presentation/_index.md
I added keywords and descriptions for all articles in this section.
> SLIDESDOC-193: Added keywords and descriptions. "Manage Presentation" section. 

- java/developer-guide/presentation-content/powerpoint-charts/chart-entities/chart-axis/_index.md
JAVA: Add "Disabling vertical axis..." article
> Slides java articles/slidesjava 38618

- java/developer-guide/presentation-content/manage-hyperlinks/_index.md
JAVA: Improve the "Manage Hyperlinks" article
> JAVA: Improve the "Manage Hyperlinks" article

- net/developer-guide/presentation-slide/convert-slide/_index.md
[SLIDESNET-42492](https://issue.lutsk.dynabic.com/issues/SLIDESNET-42492)
> SLIDESNET-42492  The code snippets with RenderToSlide method added to the "Convert Slide" article.

- net/developer-guide/manage-presentation/convert-presentation/export-to-xaml/_index.md
> Fix for failed build

- cpp/developer-guide/presentation-content/powerpoint-charts/chart-entities/chart-axis/_index.md
[SLIDESCPP-3110](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3110)
> SLIDESCPP-3110 Updated "Chart Axis" article

- cpp/developer-guide/presentation-content/manage-hyperlinks/_index.md
[SLIDESCPP-3111](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3111)
> SLIDESCPP-3111 Updated "Manage Hyperlinks" article

- cpp/developer-guide/presentation-slide/convert-slide/_index.md
[SLIDESCPP-2919](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-2919)
> SLIDESCPP-2919 Updated "Convert Slide" article

- java/developer-guide/presentation-design/powerpoint-fonts/manage-font/_index.md
Removed GISTS from Manage Fonts article
> Removed GISTS from Manage Fonts article

- net/developer-guide/presentation-content/manage-text/manage-textbox/_index.md
Added information on adding text or text frame to a slide, corrected errors, and then rewrote the entire article.
> SLIDESDOC-203: Text in a shape - text box 

- net/developer-guide/presentation-content/manage-blob/_index.md
Added new sections and details, reviewed the article to correct errors in texts and code comments, and restructured and rewrote the entire article.
> SLIDESDOC-204: Memory consumption and  BLOB. 

- java/developer-guide/presentation-content/manage-media-files/audio-frame/_index.md
- java/developer-guide/presentation-slide/convert-slide/_index.md
Add RenderToGraphics methods to Convert Slide article
> Add RenderToGraphics methods to Convert Slide article

- androidjava/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2021/aspose-slides-for-android-via-java-21-9-release-notes/_index.md
- jasperreports/release-notes/release-notes-2021/aspose-slides-for-jasper-reports-21-9-release-notes/_index.md
- java/release-notes/aspose-slides-for-java/release-notes-2021/aspose-slides-for-java-21-9-release-notes/_index.md
Aspose.Slides for Java/JasperReports/Android via Java 21.9 Release Notes
> Slides java 2021/aspose slides 21 9 release notes

- java/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/render-a-slide-as-an-svg-image/_index.md
Added Render a slide as an svg image article
> Added Render a slide as an svg image article

- cpp/_index.md
- java/_index.md
- net/_index.md
Some corrections for links and texts.
> SLIDESDOC-198-Corrections for .NET, Java, and CPP

- cpp/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/render-a-slide-as-an-svg-image/_index.md
[SLIDESCPP-3144](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3144)
> SLIDESCPP-3144 Added "Render Slide As SVG" article for C++

- java/developer-guide/presentation-content/manage-text/manage-textbox/_index.md
JAVA: Text in a shape - text box
> JAVA: Text in a shape - text box

- java/developer-guide/presentation-content/manage-blob/_index.md
Java: Update article about performance and memory consumption
> Java: Update article about performance and memory consumption

- java/developer-guide/presentation-design/presentation-header-and-footer/_index.md
Fixed example for Manage Header and Footer in Presentation
> JAVA: Fixed example for Manage Header and Footer in Presentation

- net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-to-png/_index.md
Added a new article on converting PowerPoint to PNG.
> SLIDESDOC-199: Added the "PowerPoint to PNG" article. 

- net/developer-guide/manage-presentation/merge-presentation/_index.md
Added a new section on "Merging Presentations with Different Slide Sizes". Rewrote the entire article
> SLIDESDOC-207: Merging presentations with different slide sizes - Merge Presentation. 

- cpp/developer-guide/technical-articles/hello-world-application-using-aspose-slides/_index.md
[SLIDESCPP-3153](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3153)
> SLIDESCPP-3153 Updated "Hello World Application using Aspose.Slides"

- cpp/release-notes/release-notes-2021/aspose-slides-for-cpp-21-10-release-notes/_index.md
Aspose.Slides for C++ 21.10 Release Notes
> Aspose.Slides for C++ 21.10 Release Notes

- net/developer-guide/3d-presentation/_index.md
- net/developer-guide/powerpoint-animation/_index.md
- net/developer-guide/presentation-comments/_index.md
- net/developer-guide/presentation-design/powerpoint-fonts/custom-font/_index.md
- net/developer-guide/presentation-design/powerpoint-fonts/default-font/_index.md
- net/developer-guide/presentation-design/powerpoint-fonts/embedded-font/_index.md
- net/developer-guide/presentation-design/powerpoint-fonts/fallback-font/_index.md
- net/developer-guide/presentation-design/powerpoint-fonts/fallback-font/create-fallback-font/_index.md
- net/developer-guide/presentation-design/powerpoint-fonts/fallback-font/create-fallback-fonts-collection/_index.md
- net/developer-guide/presentation-design/powerpoint-fonts/fallback-font/render-presentation-with-fallback-font/_index.md
- net/developer-guide/presentation-design/powerpoint-fonts/font-replacement/_index.md
- net/developer-guide/presentation-design/powerpoint-fonts/font-substitution/_index.md
- net/developer-guide/presentation-design/presentation-background/_index.md
- net/developer-guide/presentation-design/presentation-header-and-footer/_index.md
- net/developer-guide/presentation-design/presentation-theme/_index.md
- net/developer-guide/presentation-notes/_index.md
- net/developer-guide/presentation-properties/_index.md
- net/developer-guide/presentation-security/digital-signature-in-powerpoint/_index.md
- net/developer-guide/presentation-security/password-protected-presentation/_index.md
- net/developer-guide/presentation-security/read-only-presentatiom/_index.md
- net/developer-guide/presentation-security/watermark/_index.md
- net/developer-guide/presentation-via-vba/_index.md
- net/developer-guide/presentation-viewer/_index.md
- net/developer-guide/presentation-viewer/presentation-view-properties/_index.md
- net/developer-guide/web-extensions/_index.md
I added suitable keywords and descriptions for articles under Presentation Design and the remaining sections.
> SLIDESDOC-193: Presentation Design and others

- cpp/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-to-png/_index.md
[SLIDESCPP-3181](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3181)
> SLIDESCPP-3181 Added "PowerPoint to PNG" article in C++.

- cpp/release-notes/release-notes-2021/aspose-slides-for-cpp-21-11-release-notes/_index.md
Aspose.Slides for C++ 21.11 Release Notes
> Aspose.Slides for C++ 21.11 Release Notes

- androidjava/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2021/aspose-slides-for-android-via-java-21-11-release-notes/_index.md
- jasperreports/release-notes/release-notes-2021/aspose-slides-for-jasper-reports-21-11-release-notes/_index.md
- java/release-notes/aspose-slides-for-java/release-notes-2021/aspose-slides-for-java-21-11-release-notes/_index.md
Aspose.Slides for Java/JasperReports/Android via Java 21.11 Release Notes
> Aspose.Slides for Java/JasperReports/Android via Java 21.11 Release Notes

- java/getting-started/installation/_index.md
- java/getting-started/system-requirements/_index.md
Rewrite/update Java installation page
> Rewrite/update Java installation page

- cpp/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-ppt-and-pptx-to-pdf-with-notes/_index.md
- cpp/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-ppt-and-pptx-to-pdf/_index.md
- java/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-ppt-and-pptx-to-pdf-with-notes/_index.md
- java/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-ppt-and-pptx-to-pdf/_index.md
- net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-to-pdf-with-notes/_index.md
- net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-to-pdf/_index.md
Added new backlinks and made important corrections
> SLIDESSEO-34: Additions and corrections for PPT to PDF backlinks

- java/developer-guide/presentation-content/manage-blob/_index.md
- java/developer-guide/presentation-content/manage-text/manage-bullet/_index.md
Minor fixes to the structure of Manage-Bullet and Manage-Text articles
> Minor fixes to the structure of Manage-Bullet and Manage-Text articles

- cpp/developer-guide/presentation-content/manage-text/manage-textbox/_index.md
[SLIDESCPP-2917](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-2917)
> SLIDESCPP-2917 Updated the "Manage TextBox" article

- cpp/developer-guide/presentation-content/manage-blob/_index.md
[SLIDESCPP-2918](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-2918)
> SLIDESCPP-2918 Updated the "Manage Blob" article

- cpp/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-ppt-and-pptx-to-doc-and-docx/_index.md
[SLIDESCPP-3182](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3182)
> SLIDESCPP-3182 Updated the "PowerPoint to Word" article in C++.

- androidjava/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2021/aspose-slides-for-android-via-java-21-12-release-notes/_index.md
- jasperreports/release-notes/release-notes-2021/aspose-slides-for-jasper-reports-21-12-release-notes/_index.md
- java/release-notes/aspose-slides-for-java/release-notes-2021/aspose-slides-for-java-21-12-release-notes/_index.md
Aspose.Slides for Java/JasperReports/Android via Java 21.12 Release Notes
> Aspose.Slides for Java/JasperReports/Android via Java 21.12 Release Notes

- cpp/release-notes/release-notes-2021/aspose-slides-for-cpp-21-12-release-notes/_index.md
Aspose.Slides for C++ 21.12 Release Notes
> Aspose.Slides for C++ 21.12 Release Notes

- net/developer-guide/presentation-content/powerpoint-shapes/shape-formatting/_index.md
I added the description on "Set Transparency".
> SLIDESDOC-214: Set Transparency - Shape formatting

- net/developer-guide/presentation-content/powerpoint-shapes/shape-types/custom-shapes/_index.md
Added the new section. Rewrote and restructured the entire article.
> SLIDESDOC-241: Custom shape with curved corners - Rewrote "Custom Shape"

- cpp/developer-guide/presentation-content/manage-media-files/image/_index.md
Please, add the needed C++ code.
> SLIDESSEO-159: PNGtoPPT and JPEGtoPPT - C++

- java/developer-guide/presentation-comments/_index.md
- net/developer-guide/presentation-comments/_index.md
Update "Presentation Comments" article in Java
> Update "Presentation Comments" article in Java

- java/developer-guide/presentation-design/powerpoint-fonts/embedded-font/_index.md
Code example in "Add Embedded Fonts to Presentation" section is wrong
> Code example in "Add Embedded Fonts to Presentation" section is wrong

- cpp/release-notes/release-notes-2018/_index.md
- cpp/release-notes/release-notes-2019/_index.md
- cpp/release-notes/release-notes-2020/_index.md
- cpp/release-notes/release-notes-2021/_index.md
- cpp/release-notes/release-notes-2022/_index.md
- cpp/release-notes/release-notes-2022/aspose-slides-for-cpp-22-1-release-notes/_index.md
Aspose.Slides for C++ 22.1 Release Notes
> Aspose.Slides for C++ 22.1 Release Notes

- androidjava/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2022/_index.md
- androidjava/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2022/aspose-slides-for-android-via-java-22-1-release-notes/_index.md
- jasperreports/release-notes/release-notes-2022/_index.md
- jasperreports/release-notes/release-notes-2022/aspose-slides-for-jasper-reports-22-1-release-notes/_index.md
- java/release-notes/aspose-slides-for-java/release-notes-2022/_index.md
- java/release-notes/aspose-slides-for-java/release-notes-2022/aspose-slides-for-java-22-1-release-notes/_index.md
Aspose.Slides for Java/JasperReports/Android via Java 22.1 Release Notes
> Aspose.Slides for Java/JasperReports/Android via Java 22.1 Release Notes

- java/developer-guide/presentation-content/powerpoint-shapes/shape-types/custom-shapes/_index.md
Rewrite the "Custom Shape" article in Java
> Rewrite the "Custom Shape" article in Java

- cpp/developer-guide/presentation-content/powerpoint-shapes/shape-types/custom-shapes/_index.md
[SLIDESCPP-3309](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3309)
> SLIDESCPP-3309 Rewrite the "Custom Shape" article in C++

- cpp/developer-guide/presentation-comments/_index.md
[SLIDESCPP-3345 ](https://issue.lutsk.dynabic.com/issues/SLIDESCPP-3345)
> SLIDESCPP-3345 Update "Presentation Comments" article in C++

- net/developer-guide/web-extensions/_index.md
@yury-knml please, pay attention to the XXX instances.
> SLIIDESDOC-252: Rewrote HTML WebExtensions

- androidjava/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2022/aspose-slides-for-android-via-java-22-2-release-notes/_index.md
- jasperreports/release-notes/release-notes-2022/aspose-slides-for-jasper-reports-22-1-release-notes/_index.md
- jasperreports/release-notes/release-notes-2022/aspose-slides-for-jasper-reports-22-2-release-notes/_index.md
- java/release-notes/aspose-slides-for-java/release-notes-2022/aspose-slides-for-java-22-2-release-notes/_index.md
Aspose.Slides for Java/JasperReports/Android via Java 22.2 Release Notes
> Aspose.Slides for Java/JasperReports/Android via Java 22.2 Release Notes

- cpp/release-notes/release-notes-2022/aspose-slides-for-cpp-22-2-release-notes/_index.md
Aspose.Slides for C++ 22.2 Release Notes
> Aspose.Slides for C++ 22.2 Release Notes

- net/developer-guide/presentation-design/powerpoint-fonts/font-replacement/_index.md
- net/developer-guide/presentation-design/powerpoint-fonts/font-substitution/_index.md
@stasmiroshnichenko Please, check the last 2 lines of code in the **Font Substitution** article.
> SLIDESDOC-269: Font replacement and substitution

- java/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-to-html/_index.md
Rewrite the "Convert PowerPoint to HTML" article in Java
> Rewrite the "Convert PowerPoint to HTML" article in Java

- java/developer-guide/manage-presentation/convert-presentation/export-to-html5/_index.md
Add "Export to HTML5 " article in Java
> Add "Export to HTML5 " article in Java

- cpp/developer-guide/presentation-content/manage-ole/_index.md
- java/developer-guide/presentation-content/manage-ole/_index.md
- net/developer-guide/presentation-content/manage-ole/_index.md
- python-net/developer-guide/presentation-content/manage-ole/_index.md
@nikolaysaulyak Please, add a C++ code sample under the **Embedding Other File Types in Slides** section and delete _XXX_.
> SLIDESDOC-284: "Manage OLE" update to N, J, C, P

- cpp/developer-guide/presentation-content/manage-media-files/picture-frame/_index.md
- java/developer-guide/presentation-content/manage-media-files/picture-frame/_index.md
- net/developer-guide/presentation-content/manage-media-files/picture-frame/_index.md
- python-net/developer-guide/presentation-content/manage-media-files/picture-frame/_index.md
@petrtetenko Please, add a Java code under the **Crop image** section in Java.
@nikolaysaulyak Please, add a C++ code under the **Crop image** section in CPP and verify that the code samples work (I replaced gist code with inline code). 
@stasmiroshnichenko Please, add a Python code under the **Crop image** section in Python
> SLIDESDOC-285: Updated "Picture Frame" in J, C, P

- cpp/developer-guide/presentation-comments/_index.md
- java/developer-guide/presentation-comments/_index.md
- net/developer-guide/presentation-comments/_index.md
- python-net/developer-guide/presentation-comments/_index.md
@petrtetenko Please add two code samples under the **Remove Comment** section in Java.
@nikolaysaulyak Please add two code samples under the **Remove Comment** section in CPP.
@stasmiroshnichenko Please add a code sample under the **Add Modern Comment** section and two code samples under the **Remove Comment** section in Python-net.
> SLIDESDOC-286: Updated Presentation Comments in J,C,P

- cpp/release-notes/release-notes-2022/aspose-slides-for-cpp-22-4-release-notes/_index.md
Aspose.Slides for C++ 22.4 Release Notes
> Aspose.Slides for C++ 22.4 Release Notes

- androidjava/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2022/aspose-slides-for-android-via-java-22-4-release-notes/_index.md
- jasperreports/release-notes/release-notes-2022/aspose-slides-for-jasper-reports-22-4-release-notes/_index.md
- java/release-notes/aspose-slides-for-java/release-notes-2022/aspose-slides-for-java-22-4-release-notes/_index.md
Aspose.Slides for Java/JasperReports/Android via Java 22.4 Release Notes
> Aspose.Slides for Java/JasperReports/Android via Java 22.4 Release Notes

- cpp/developer-guide/presentation-content/manage-media-files/picture-frame/_index.md
- java/developer-guide/presentation-content/manage-media-files/picture-frame/_index.md
- net/developer-guide/presentation-content/manage-media-files/picture-frame/_index.md
- python-net/developer-guide/presentation-content/manage-media-files/picture-frame/_index.md
@nikolaysaulyak, Please add the relevant C++ code under the **Add Image as Link** section. 
@petrtetenko, Please add the relevant Java code under the **Add Image as Link** section. 
@stasmiroshnichenko Please add the relevant Python code under the **Add Image as Link** section.
> SLIDESDOC-247: Insert image as link

- androidjava/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2022/aspose-slides-for-android-via-java-22-5-release-notes/_index.md
- jasperreports/release-notes/release-notes-2022/aspose-slides-for-jasper-reports-22-5-release-notes/_index.md
- java/release-notes/aspose-slides-for-java/release-notes-2022/aspose-slides-for-java-22-5-release-notes/_index.md
Aspose.Slides for Java/JasperReports/Android via Java 22.5 Release Notes
> Aspose.Slides for Java/JasperReports/Android via Java 22.5 Release Notes

- cpp/release-notes/release-notes-2022/aspose-slides-for-cpp-22-5-release-notes/_index.md
Aspose.Slides for C++ 22.5 Release Notes
> Aspose.Slides for C++ 22.5 Release Notes

- net/developer-guide/manage-presentation/convert-presentation/export-to-html5/_index.md
@yury-knml Please, check and confirm that the C# code is okay.
> SLIDESDOC-266: Slideview HTML5 Export

- net/developer-guide/presentation-content/manage-media-files/picture-frame/_index.md
@yury-knml The code under Use StretchOff Property was wrong, so I deleted it. Please add the correct code.
> SLIDESDOC-238: Correct code for StretchOff property in Picture Frame

- cpp/developer-guide/presentation-content/powerpoint-charts/create-chart/_index.md
- java/developer-guide/presentation-content/powerpoint-charts/create-chart/_index.md
- net/developer-guide/presentation-content/powerpoint-charts/create-chart/_index.md
- python-net/developer-guide/presentation-content/powerpoint-charts/create-chart/_index.md
@petrtetenko Please add a Java code for **Creating Radar charts**
@nikolaysaulyak Please add a C++ code for **Creating Radar charts**
@stasmiroshnichenko Please add a Python code for **Creating Radar charts**
> SLIDESDOC-290: Radar chart - rewrote "Create Charts" for J, C, and P

- net/developer-guide/presentation-content/powerpoint-charts/chart-workbook/_index.md
@yury-knml please add the C# code for **Specify Data Source Type**.
> SLIDESDOC-264: Specify data source type - Chart Workbook

- cpp/release-notes/release-notes-2022/aspose-slides-for-cpp-22-6-release-notes/_index.md
Aspose.Slides for C++ 22.6 Release Notes
> Aspose.Slides for C++ 22.6 Release Notes

- net/developer-guide/presentation-content/powerpoint-charts/create-chart/_index.md
@yury-knml Please add a sample code and screenshot under **Map Chart**.
> SLIDESDOC-294: Map Chart - Create Chart

- cpp/developer-guide/presentation-content/manage-text/manage-placeholder/_index.md
- java/developer-guide/presentation-content/manage-text/manage-placeholder/_index.md
- net/developer-guide/presentation-content/manage-text/manage-placeholder/_index.md
- python-net/developer-guide/presentation-content/manage-text/manage-placeholder/_index.md
@yury-knml Please add a C# code snippet under **Set Placeholder Image Transparency**
@nikolaysaulyak  Please add a C++ code snippet under **Set Placeholder Image Transparency**
@stasmiroshnichenko  Please add a Python code snippet under **Set Placeholder Image Transparency**
> SLIDESDOC-301: Placeholder transparency

- androidjava/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2022/aspose-slides-for-android-via-java-22-7-release-notes/_index.md
- jasperreports/release-notes/release-notes-2022/aspose-slides-for-jasper-reports-22-7-release-notes/_index.md
- java/release-notes/aspose-slides-for-java/release-notes-2022/aspose-slides-for-java-22-7-release-notes/_index.md
- php-java/release-notes/release-notes-2022/aspose-slides-for-php-via-java-22-7-release-notes/_index.md
Aspose.Slides for Java/JasperReports/Android/PHP 22.7 Release Notes
> Aspose.Slides for Java/JasperReports/Android/PHP 22.7 Release Notes

- cpp/developer-guide/manage-presentation/convert-presentation/export-to-html5/_index.md
- java/developer-guide/manage-presentation/convert-presentation/export-to-html5/_index.md
- python-net/developer-guide/manage-presentation/convert-presentation/export-to-html5/_index.md
@stasmiroshnichenko Please add a Python snippet under **Export PowerPoint to HTML5 Slide View**.
@petrtetenko Please add a Java snippet under **Export PowerPoint to HTML5 Slide View**.
@nikolaysaulyak Please add a C++ snippet under **Export PowerPoint to HTML5 Slide View**.
> SLIDESDOC-308: HTML5 Slide View in J, C, P

- net/developer-guide/presentation-content/powerpoint-shapes/shape-animation/_index.md
[SLIDESNET-43343](https://issue.lutsk.dynabic.com/issues/SLIDESNET-43343)
> SLIDESNET-43343  "Extract Animation Effect Sound" section added to Shape Animation" article.

- net/developer-guide/presentation-slide/slide-transition/_index.md
[SLIDESNET-43357](https://issue.lutsk.dynabic.com/issues/SLIDESNET-43357)
> SLIDESNET-43357 AdvancedAfter code snippet added to "Slide transition" article.

- cpp/developer-guide/presentation-content/powerpoint-shapes/shape-formatting/_index.md
- java/developer-guide/presentation-content/powerpoint-shapes/shape-formatting/_index.md
- net/developer-guide/presentation-content/powerpoint-shapes/shape-formatting/_index.md
- python-net/developer-guide/presentation-content/powerpoint-shapes/shape-formatting/_index.md
@yury-knml Please, add a code snippet under **Reset Formatting**.
> SLIDESDOC-321: Reset Formatting - Shape formatting

- cpp/release-notes/release-notes-2022/aspose-slides-for-cpp-22-9-release-notes/_index.md
Aspose.Slides for C++ 22.9 Release Notes
> Aspose.Slides for C++ 22.9 Release Notes

- androidjava/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2022/aspose-slides-for-android-via-java-22-9-release-notes/_index.md
- jasperreports/release-notes/release-notes-2022/aspose-slides-for-jasper-reports-22-9-release-notes/_index.md
- java/release-notes/aspose-slides-for-java/release-notes-2022/aspose-slides-for-java-22-9-release-notes/_index.md
- php-java/release-notes/release-notes-2022/aspose-slides-for-php-via-java-22-9-release-notes/_index.md
Aspose.Slides for Java/JasperReports/Android/PHP 22.9 Release Notes
> Aspose.Slides for Java/JasperReports/Android/PHP 22.9 Release Notes

- net/developer-guide/presentation-design/powerpoint-fonts/font-substitution/_index.md
> SLIDESNET-43397: Improved "Font Substitution"

- androidjava/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2022/aspose-slides-for-android-via-java-22-10-release-notes/_index.md
- jasperreports/release-notes/release-notes-2022/aspose-slides-for-jasper-reports-22-10-release-notes/_index.md
- java/release-notes/aspose-slides-for-java/release-notes-2022/aspose-slides-for-java-22-10-release-notes/_index.md
- php-java/release-notes/release-notes-2022/aspose-slides-for-php-via-java-22-10-release-notes/_index.md
Aspose.Slides for Java/JasperReports/Android/PHP 22.10 Release Notes
> Aspose.Slides for Java/JasperReports/Android/PHP 22.10 Release Notes

- cpp/release-notes/release-notes-2022/aspose-slides-for-cpp-22-10-release-notes/_index.md
Aspose.Slides for C++ 22.10 Release Notes
> Aspose.Slides for C++ 22.10 Release Notes

- cpp/release-notes/release-notes-2022/aspose-slides-for-cpp-22-11-release-notes/_index.md
Aspose.Slides for C++ 22.11 Release Notes
> Aspose.Slides for C++ 22.11 Release Notes

- net/developer-guide/presentation-content/manage-hyperlinks/_index.md
[SLIDESNET-43484](https://issue.lutsk.dynabic.com/issues/SLIDESNET-43484)
> SLIDESNET-43484 The IHyperlink.Sound and IHyperlink.StopSoundOnClick properties added to "Manage Hyperlinks" article.

- cpp/developer-guide/manage-presentation/import-presentation/_index.md
- java/developer-guide/manage-presentation/import-presentation/_index.md
- net/developer-guide/manage-presentation/import-presentation/_index.md
- python-net/developer-guide/manage-presentation/import-presentation/_index.md
@stasmiroshnichenko Please search for xxx and add the relevant Python code and then delete xxx.
@petrtetenko Please search for xxx and add the relevant Java code and then delete xxx.
@nikolaysaulyak Please search for xxx and add the relevant C++ code and then delete xxx.
> SLIDESDOC-346: "Import Presentation" - N, J, C, P

- cpp/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-to-jpg/_index.md
- java/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-to-jpg/_index.md
- net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-to-jpg/_index.md
- python-net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-to-jpg/_index.md
@nikolaysaulyak Please search for xxx and add the relevant C++ code and then delete xxx.
> SLIDESDOC-330: Rewrote the "PPT to JPG" article

- .gitignore
- androidjava/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2022/aspose-slides-for-android-via-java-22-11-release-notes/_index.md
- androidjava/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2022/aspose-slides-for-android-via-java-22-12-release-notes/_index.md
- jasperreports/release-notes/release-notes-2022/aspose-slides-for-jasper-reports-22-12-release-notes/_index.md
- java/release-notes/aspose-slides-for-java/release-notes-2022/aspose-slides-for-java-22-12-release-notes/_index.md
- php-java/release-notes/release-notes-2022/aspose-slides-for-php-via-java-22-12-release-notes/_index.md
Aspose.Slides for Java/JasperReports/Android/PHP 22.12 Release Notes
> Aspose.Slides for Java/JasperReports/Android/PHP 22.12 Release Notes

- cpp/release-notes/release-notes-2022/aspose-slides-for-cpp-22-12-release-notes/_index.md
Aspose.Slides for C++ 22.12 Release Notes
> Aspose.Slides for C++ 22.12 Release Notes

- cpp/developer-guide/manage-presentation/examine-presentation/_index.md
- cpp/developer-guide/presentation-security/password-protected-presentation/_index.md
- java/developer-guide/manage-presentation/examine-presentation/_index.md
- java/developer-guide/presentation-security/password-protected-presentation/_index.md
- net/developer-guide/manage-presentation/examine-presentation/_index.md
- net/developer-guide/presentation-security/password-protected-presentation/_index.md
- python-net/developer-guide/manage-presentation/examine-presentation/_index.md
- python-net/developer-guide/presentation-security/password-protected-presentation/_index.md
The C# code is in this branch.
@stasmiroshnichenko Please search for xxx in the **Password Protected Presentation** article, add the relevant Python code, and then delete xxx.
@petrtetenko Please search for xxx in the **Password Protected Presentation** article, add the relevant Java code, and then delete xxx.
@nikolaysaulyak Please search for xxx in the **Password Protected Presentation** article, add the relevant C++ code, and then delete xxx.
> SLIDESDOC-347: Is presentation password protected?

- cpp/developer-guide/presentation-content/manage-media-files/picture-frame/_index.md
- java/developer-guide/presentation-content/manage-media-files/picture-frame/_index.md
- net/developer-guide/presentation-content/manage-media-files/picture-frame/_index.md
- python-net/developer-guide/presentation-content/manage-media-files/picture-frame/_index.md
The C# code is in this branch.
@stasmiroshnichenko Please search for xxx, add the relevant Python code, and then delete xxx.
@nikolaysaulyak Please search for xxx, add the relevant C++ code, and then delete xxx.
> SLIDESDOC-354: Get image transparency - Picture frame

- cpp/release-notes/release-notes-2023/_index.md
- cpp/release-notes/release-notes-2023/aspose-slides-for-cpp-23-1-release-notes/_index.md
Aspose.Slides for C++ 23.1 Release Notes
> Aspose.Slides for C++ 23.1 Release Notes

- androidjava/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2021/aspose-slides-for-android-via-java-21-11-release-notes/_index.md
- androidjava/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2021/aspose-slides-for-android-via-java-21-12-release-notes/_index.md
- androidjava/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2021/aspose-slides-for-android-via-java-21-5-release-notes/_index.md
- androidjava/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2021/aspose-slides-for-android-via-java-21-6-release-notes/_index.md
- androidjava/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2021/aspose-slides-for-android-via-java-21-7-release-notes/_index.md
- androidjava/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2021/aspose-slides-for-android-via-java-21-8-release-notes/_index.md
- androidjava/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2023/_index.md
- androidjava/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2023/aspose-slides-for-android-via-java-23-1-release-notes/_index.md
- jasperreports/release-notes/release-notes-2023/_index.md
- jasperreports/release-notes/release-notes-2023/aspose-slides-for-jasper-reports-23-1-release-notes/_index.md
- java/release-notes/aspose-slides-for-java/release-notes-2023/_index.md
- java/release-notes/aspose-slides-for-java/release-notes-2023/aspose-slides-for-java-23-1-release-notes/_index.md
- php-java/release-notes/release-notes-2022/_index.md
- php-java/release-notes/release-notes-2023/_index.md
- php-java/release-notes/release-notes-2023/aspose-slides-for-php-via-java-23-1-release-notes/_index.md
Aspose.Slides for Java/JasperReports/Android/PHP 23.1 Release Notes
> Aspose.Slides for Java/JasperReports/Android/PHP 23.1 Release Notes

- cpp/release-notes/release-notes-2023/aspose-slides-for-cpp-23-2-release-notes/_index.md
Aspose.Slides for C++ 23.2 Release Notes
> Aspose.Slides for C++ 23.2 Release Notes

- cpp/developer-guide/presentation-content/manage-text/text-formatting/_index.md
- java/developer-guide/presentation-content/manage-text/text-formatting/_index.md
- net/developer-guide/presentation-content/manage-text/text-formatting/_index.md
- python-net/developer-guide/presentation-content/manage-text/text-formatting/_index.md
The C# code is in this branch.
@stasmiroshnichenko Please search for xxx, add the relevant Python code, and then delete xxx.
@petrtetenko Please search for xxx, add the relevant Java code, and then delete xxx.
@nikolaysaulyak Please search for xxx, add the relevant C++ code, and then delete xxx.
> SLIDESDOC-358: Change font size for text in paragraph

- androidjava/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2023/aspose-slides-for-android-via-java-23-2-release-notes/_index.md
- jasperreports/release-notes/release-notes-2023/aspose-slides-for-jasper-reports-23-2-release-notes/_index.md
- java/release-notes/aspose-slides-for-java/release-notes-2023/aspose-slides-for-java-23-2-release-notes/_index.md
- php-java/release-notes/release-notes-2023/aspose-slides-for-php-via-java-23-2-release-notes/_index.md
Aspose.Slides for Java/JasperReports/Android/PHP 23.2 Release Notes
> Aspose.Slides for Java/JasperReports/Android/PHP 23.2 Release Notes

- androidjava/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2023/aspose-slides-for-android-via-java-23-4-release-notes/_index.md
- jasperreports/release-notes/release-notes-2023/aspose-slides-for-jasper-reports-23-4-release-notes/_index.md
- java/release-notes/aspose-slides-for-java/release-notes-2023/aspose-slides-for-java-23-4-release-notes/_index.md
- php-java/release-notes/release-notes-2023/aspose-slides-for-php-via-java-23-4-release-notes/_index.md
Aspose.Slides for Java/JasperReports/Android/PHP 23.4 Release Notes
> Aspose.Slides for Java/JasperReports/Android/PHP 23.4 Release Notes

- cpp/release-notes/release-notes-2023/aspose-slides-for-cpp-23-4-release-notes/_index.md
Aspose.Slides for C++ 23.4 Release Notes
> Aspose.Slides for C++ 23.4 Release Notes

- cpp/developer-guide/presentation-content/manage-text/text-formatting/_index.md
- java/developer-guide/presentation-content/manage-text/text-formatting/_index.md
- net/developer-guide/presentation-content/manage-text/text-formatting/_index.md
- python-net/developer-guide/presentation-content/manage-text/text-formatting/_index.md
@yury-knml Please search for xxx and provide the code samples.
> SLIDEESDOC-358: Change text font size in N, J, C, P

- cpp/developer-guide/presentation-content/manage-text/text-formatting/_index.md
- java/developer-guide/presentation-content/manage-text/text-formatting/_index.md
- net/developer-guide/presentation-content/manage-text/text-formatting/_index.md
- python-net/developer-guide/presentation-content/manage-text/text-formatting/_index.md
@yury-knml Please search for xxx and provide the code samples.
> SLIDESDOC-378: Set text background color in N, J, C, P

- cpp/release-notes/release-notes-2023/aspose-slides-for-cpp-23-6-release-notes/_index.md
Aspose.Slides for C++ 23.6 Release Notes
> Aspose.Slides for C++ 23.6 Release Notes

- net/developer-guide/presentation-content/manage-ole/_index.md
[SLIDESNET-43559](https://issue.lutsk.dynabic.com/issues/SLIDESNET-43559)
> SLIDESNET-43559: The IOleObjectFrame.LinkPathLong and IOleObjectFrame.LinkPathRelative properties added to "Manage OLE" article.

- androidjava/release-notes/aspose-slides-for-android-via-java/android-via-java-release-notes-2023/aspose-slides-for-android-via-java-23-8-release-notes/_index.md
- jasperreports/release-notes/release-notes-2023/aspose-slides-for-jasper-reports-23-8-release-notes/_index.md
- java/release-notes/aspose-slides-for-java/release-notes-2023/aspose-slides-for-java-23-8-release-notes/_index.md
- php-java/release-notes/release-notes-2023/aspose-slides-for-php-via-java-23-8-release-notes/_index.md
Aspose.Slides for Java/JasperReports/Android/PHP 23.8 Release Notes
> Aspose.Slides for Java/JasperReports/Android/PHP 23.8 Release Notes

- cpp/release-notes/release-notes-2023/aspose-slides-for-cpp-23-8-release-notes/_index.md
Aspose.Slides for C++ 23.8 Release Notes
> Aspose.Slides for C++ 23.8 Release Notes

- cpp/developer-guide/presentation-design/powerpoint-fonts/custom-font/_index.md
- java/developer-guide/presentation-design/powerpoint-fonts/custom-font/_index.md
- net/developer-guide/presentation-design/powerpoint-fonts/custom-font/_index.md
- python-net/developer-guide/presentation-design/powerpoint-fonts/custom-font/_index.md
@yury-knml Please provide the C# snippet.
> SLIDESDOC-356: Supported fonts - Rewrote "Custom fonts"

- net/release-notes/release-notes-2023/aspose-slides-for-net-23-10-release-notes/_index.md
> Aspose Slides release note for 23.10 - SLIDESNET-43994 removed

- cpp/release-notes/release-notes-2023/aspose-slides-for-cpp-23-10-release-notes/_index.md
Aspose.Slides for C++ 23.10 Release Notes
> Aspose.Slides for C++ 23.10 Release Notes

- cpp/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-to-tiff/_index.md
- java/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-to-tiff/_index.md
- net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-to-tiff/_index.md
- python-net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-to-tiff/_index.md
@petrtetenko Please provide the Java code and delete xxx
@valentynlukianets-aspose @nikolaysaulyak Please provide the C++ code and delete xxx
@stasmiroshnichenko Please provide the Python code and delete xxx
> SLIDESDOC-414: Convert PowerPoint to TIFF

- reportingservices/getting-started/frequently-asked-questions/_index.md
SLIDESDOC-430. ReportingServices FAQs article has been added.
> SLIDESDOC-430. ReportingServices FAQs article has been added.

- nodejs-java/getting-started/installation/_index.md
- nodejs-java/getting-started/troubleshooting-installtion/_index.md
Added new troubleshooting-installation article
Corrected Installation article:
- added project initialization (according to Andrey's comments)
- added link to troubleshooting-installation article
> Added troubleshooting-installation article

- cpp/developer-guide/presentation-slide/slide-master/_index.md
- java/developer-guide/presentation-slide/slide-master/_index.md
- net/developer-guide/presentation-slide/slide-master/_index.md
- python-net/developer-guide/presentation-slide/slide-master/_index.md
Please search for xxx and add the relevant snippets.
> SLIDESDOC-316L: Rewrote "Slide Master"

- java/getting-started/licensing-bug/_index.md
> Slides java articles/slidesjava 39401 licensing bug

- net/developer-guide/presentation-via-vba/_index.md
[SLIDESNET-44496](https://issue.lutsk.dynabic.com/issues/SLIDESNET-44496)
> SLIDESNET-44496: IVbaProject.IsPasswordProtected property added to "Presentation via VBA" article

- androidjava/getting-started/supported-file-formats/_index.md
- cpp/getting-started/supported-file-formats/_index.md
- java/getting-started/supported-file-formats/_index.md
- net/getting-started/supported-file-formats/_index.md
- nodejs-java/getting-started/supported-file-formats/_index.md
- nodejs-net/getting-started/supported-file-formats/_index.md
- php-java/getting-started/supported-file-formats/_index.md
- python-java/getting-started/supported-file-formats/_index.md
- python-net/getting-started/supported-file-formats/_index.md
The article "Supported File Formats" (.NET version) is updated: 
- Format descriptions are improved.
- The FODP, MD, and XML formats are added.
> SLIDESDOC-465 The articles "Supported File Formats" are updated

- net/developer-guide/manage-presentation/open-presentation/_index.md
[SLIDESNET-44619](https://issue.lutsk.dynabic.com/issues/SLIDESNET-44619)
> SLIDESNET-44619: The ILoadOptions.DeleteEmbeddedBinaryObjects property added to "Open Presentation" article

- net/developer-guide/manage-presentation/save-presentation/_index.md
[SLIDESNET-44497](https://issue.lutsk.dynabic.com/issues/SLIDESNET-44497)
> SLIDESNET-44497: The IPptxOptions.Zip64Mode property added to "Save Presentation" article

- php-java/getting-started/installation/_index.md
Added a paragraph about using Docker to the PHP installation article
> SLIDESDOC-479 Added a paragraph about using Docker to the PHP installation article

- androidjava/developer-guide/technical-articles/multithreading/_index.md
- cpp/developer-guide/technical-articles/multithreading/_index.md
- java/developer-guide/technical-articles/multithreading/_index.md
- net/developer-guide/technical-articles/multithreading/_index.md
- php-java/developer-guide/technical-articles/multithreading/_index.md
- python-net/developer-guide/technical-articles/multithreading/_index.md
Added keywords and the section "Convert Presentation Slides to Images in Parallel" to the technical article "Multithreading in Aspose.Slides" (.NET).
> SLIDESDOC-476 Parallel conversion of presentation slides into images

- en/androidjava/developer-guide/presentation-content/powerpoint-shapes/shape-types/custom-shapes/_index.md
- en/cpp/developer-guide/presentation-content/powerpoint-shapes/shape-types/custom-shapes/_index.md
- en/java/developer-guide/presentation-content/powerpoint-shapes/shape-types/custom-shapes/_index.md
- en/net/developer-guide/presentation-content/powerpoint-shapes/shape-types/custom-shapes/_index.md
- en/php-java/developer-guide/presentation-content/powerpoint-shapes/shape-types/custom-shapes/_index.md
- en/python-net/developer-guide/presentation-content/powerpoint-shapes/shape-types/custom-shapes/_index.md
Added the section "Find Out If a Shape Geometry Is Closed" (.NET).
> SLIDESDOC-419 Find out if a shape geometry is closed

- en/androidjava/developer-guide/presentation-content/manage-media-files/picture-frame/_index.md
- en/cpp/developer-guide/presentation-content/manage-media-files/picture-frame/_index.md
- en/java/developer-guide/presentation-content/manage-media-files/picture-frame/_index.md
- en/net/developer-guide/presentation-content/manage-media-files/picture-frame/_index.md
- en/nodejs-java/developer-guide/presentation-content/manage-media-files/picture-frame/_index.md
- en/php-java/developer-guide/presentation-content/manage-media-files/picture-frame/_index.md
- en/python-net/developer-guide/presentation-content/manage-media-files/picture-frame/_index.md
Added the API reference to all effects applied to images in the section "Get Transparency of Image" in the article "Picture Frame" (.NET, C++, Python via .NET). 
Minor corrections.
> SLIDESDOC-511 Get effects applied to an image

- en/net/developer-guide/presentation-properties/_index.md
Deleted the section "Check if Presentation is Modified or Created" from the article "Presentation Properties".
> SLIDESDOC-387 The "Check if Presentation is Modified or Created" example looks incomplete

- en/net/developer-guide/manage-presentation/manage-slide-show/_index.md
Added the article "Manage Slide Show".
> SLIDESDOC-336 Create article describing new Slide Show Settings API

- en/net/developer-guide/presentation-content/manage-text/manage-textbox/_index.md
Added information to the section "Check for Text Box Shape" in the article "Manage TextBox". 
Made some minor corrections.
> SLIDESDOC-472 Detecting if a rectangle is a "real" text box

- en/androidjava/developer-guide/manage-presentation/manage-slide-show/_index.md
- en/cpp/developer-guide/manage-presentation/manage-slide-show/_index.md
- en/java/developer-guide/manage-presentation/manage-slide-show/_index.md
- en/nodejs-java/developer-guide/manage-presentation/manage-slide-show/_index.md
- en/php-java/developer-guide/manage-presentation/manage-slide-show/_index.md
- en/python-net/developer-guide/manage-presentation/manage-slide-show/_index.md
Added the article "Manage Slide Show" (Android via Java, C++, Java, Node.js via Java, PHP via Java, Python via .NET).
The previous pull request: https://github.com/aspose-slides/Aspose.Slides-Documentation/pull/667
> SLIDESDOC-336 Add an article describing new Slide Show Settings API

- en/net/developer-guide/presentation-content/powerpoint-shapes/shape-formatting/_index.md
- en/net/developer-guide/presentation-design/presentation-background/_index.md
[SLIDESNET-44650](https://issue.lutsk.dynabic.com/issues/SLIDESNET-44650)
> SLIDESNET-44650: The IPictureFillFormat Tile properties added to "Shape Formatting" and "Presentation Background" articles.

- en/net/developer-guide/technical-articles/getting-warning-callbacks-for-fonts-substitution-in-aspose-slides/_index.md
Update the article: "Getting Warning Callbacks for Fonts Substitution in Aspose.Slides"
> SLIDESNET-44632: Update the article: "Getting Warning Callbacks for Fonts Substitution in Aspose.Slides"

- en/net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-in-Handout-mode/_index.md
- en/net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-to-pdf-with-notes/_index.md
- en/net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-to-pdf/_index.md
- en/net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-to-tiff-with-notes/_index.md
- en/net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-to-tiff/_index.md
- en/net/developer-guide/presentation-slide/convert-slide/_index.md
Corrected articles on rendering notes and comments. Added article on Handout rendering.
Task: https://issue.lutsk.dynabic.com/issues/SLIDESNET-44807
> Corrected articles on rendering notes and comments. Added article on Handout rendering.

- en/net/developer-guide/manage-presentation/save-presentation/_index.md
[SLIDESNET-44809](https://issue.lutsk.dynabic.com/issues/SLIDESNET-44809)
> SLIDESNET-44809: The IPptxOptions.RefreshThumbnail property added to "Save Presentation" article.

- en/androidjava/developer-guide/presentation-content/manage-ole/_index.md
- en/cpp/developer-guide/presentation-content/manage-ole/_index.md
- en/java/developer-guide/presentation-content/manage-ole/_index.md
- en/net/developer-guide/presentation-content/manage-ole/_index.md
- en/nodejs-java/developer-guide/presentation-content/manage-ole/_index.md
- en/php-java/developer-guide/presentation-content/manage-ole/_index.md
- en/python-net/developer-guide/presentation-content/manage-ole/_index.md
Updated the article "Manage OLE".
> SLIDESDOC-392 Update the article "Manage OLE"

- en/androidjava/developer-guide/technical-articles/working-solution-for-worksheet-resizing/_index.md
- en/cpp/developer-guide/technical-articles/working-solution-for-worksheet-resizing/_index.md
- en/java/developer-guide/technical-articles/working-solution-for-worksheet-resizing/_index.md
- en/net/developer-guide/technical-articles/working-solution-for-worksheet-resizing/_index.md
- en/python-net/developer-guide/technical-articles/working-solution-for-worksheet-resizing/_index.md
Updated the article "Working Solution for Worksheet Resizing".
> SLIDESDOC-502 Add articles "Working Solution for Worksheet Resizing"

- en/java/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-to-jpg/_index.md
- en/net/developer-guide/presentation-slide/slide-master/_index.md
> Titles, descriptions updated for articles PowerPoint to PDF and Slides master

- en/net/developer-guide/presentation-security/watermark/_index.md
Updated the title, keywords, and description.
Added text.
Added comments to code examples.
> SLIDESDOC-527 Improve CTR for the article "Watermark"

- en/python-net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-to-video/_index.md
Updated the title, keywords, description, text, and code examples.
> SLIDESDOC-528 Improve CTR for the article "Convert PowerPoint to Video"

- en/net/developer-guide/presentation-content/powerpoint-math-equations/_index.md
Updated the title, keywords, description, text, and code examples. 
Added a FAQs section.
> SLIDESDOC-529 Improve CTR for the article "PowerPoint Math Equations"

- en/net/developer-guide/presentation-security/password-protected-presentation/_index.md
Updated the title, keywords, description, section headers, article structure, text and code examples. 
Added the section "FAQs".
> SLIDESDOC-532 Improve CTR for the article "Password Protected Presentation"

- en/java/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-to-pdf/_index.md
- en/net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-to-pdf/_index.md
- en/python-net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-to-pdf/_index.md
Updated the title, keywords, description, text, and code examples. 
Added the section "Frequently Asked Questions".
> SLIDESDOC-537 Improve CTR for the article "Convert PowerPoint to PDF in Java"

- en/net/developer-guide/powerpoint-animation/_index.md
Updated the title, keywords, description, and text.
> SLIDESDOC-535 Improve CTR for the article "PowerPoint Animation"

- en/net/developer-guide/presentation-content/manage-text/manage-autofit-settings/_index.md
Updated the title, keywords, description, text, and code examples.
> SLIDESDOC-550 Improve CTR for the article "Manage Autofit Settings"

- en/net/developer-guide/presentation-content/manage-text/extract-text-from-presentation/_index.md
Updated the title, keywords, description, text, and code examples. 
> SLIDESDOC-551 Improve CTR for the article "Extract Text from Presentation"

- en/net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-to-video/_index.md
- en/python-net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-to-video/_index.md
Updated the article to reflect changes made to the article for the Python version.
> SLIDESDOC-559 Improve CTR for the article "Convert PowerPoint to Video"

- en/net/developer-guide/manage-presentation/convert-presentation/convert-openoffice-odp/_index.md
Updated the title, keywords, description, text, and code example. 
> SLIDESDOC-560 Improve CTR for the article "Convert OpenOffice ODP"

- en/java/developer-guide/manage-presentation/merge-presentation/_index.md
Updated the title, keywords, description, text, and code examples. 
> SLIDESDOC-564 Improve CTR for the article "Merge Presentation"

- en/net/developer-guide/presentation-viewer/_index.md
Updated the title, keywords, description, and text. 
> SLIDESDOC-566 Improve CTR for the article "Presentation Viewer"

- en/androidjava/developer-guide/manage-presentation/merge-presentation/_index.md
- en/cpp/developer-guide/manage-presentation/merge-presentation/_index.md
- en/net/developer-guide/manage-presentation/merge-presentation/_index.md
- en/nodejs-java/developer-guide/manage-presentation/merge-presentation/_index.md
- en/php-java/developer-guide/manage-presentation/merge-presentation/_index.md
- en/python-net/developer-guide/manage-presentation/merge-presentation/_index.md
Updated code examples for Android via Java, C++, .NET, Node.js via Java, PHP via Java, and Python via .NET (the source code example is used from the Java version).
> SLIDESDOC-565 Code examples are the same in the article "Efficiently Merge PowerPoint Presentations (PPT, PPTX) with C#"

- en/nodejs-java/getting-started/installation/_index.md
SLIDESJAVA-39647 Update nodejs installation article
> SLIDESJAVA-39647 Update nodejs installation article

- en/net/developer-guide/presentation-content/powerpoint-charts/create-chart/_index.md
[SLIDESNET-44931](https://issue.lutsk.dynabic.com/issues/SLIDESNET-44931)
> SLIDESNET-44931: Update the code snippet for the combination chart (to match the example shown in the picture)

- en/java/getting-started/installation/_index.md
Added keywords and description to the meta information, and "Overview" and "FAQs" sections. 
Updated section headers and text.
> SLIDESDOC-576 Improve CTR for the article "Installation" (Java)

- en/php-java/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-to-markdown/_index.md
Updated the title, keywords, description, section headers, text, and code examples. 
Added an "Overview" and "FAQs" sections.
Fixed links.
> SLIDESDOC-578 Improve CTR for the article "Convert PowerPoint to Markdown" (PHP via Java)

- en/androidjava/developer-guide/presentation-content/manage-media-files/picture-frame/_index.md
- en/cpp/developer-guide/presentation-content/manage-media-files/picture-frame/_index.md
- en/java/developer-guide/presentation-content/manage-media-files/picture-frame/_index.md
- en/net/developer-guide/presentation-content/manage-media-files/picture-frame/_index.md
- en/nodejs-java/developer-guide/presentation-content/manage-media-files/picture-frame/_index.md
- en/php-java/developer-guide/presentation-content/manage-media-files/picture-frame/_index.md
- en/python-net/developer-guide/presentation-content/manage-media-files/picture-frame/_index.md
Renamed the section "Extract Image from Picture Frame" to "Extract Raster Images from Picture Frames" in the article "Picture Frame".
Added the section "Extract SVG Images from Picture Frames".
> SLIDESDOC-534 Extracting SVG images from presentations

- de/python-net/developer-guide/presentation-content/manage-text/superscript-and-subscript/_index.md
- en/python-net/developer-guide/manage-presentation/open-presentation/_index.md
- en/python-net/developer-guide/presentation-content/powerpoint-math-equations/_index.md
- en/python-net/developer-guide/presentation-slide/slide-layout/_index.md
- ja/python-net/developer-guide/presentation-content/manage-text/manage-paragraph/_index.md
- ja/python-net/developer-guide/presentation-design/presentation-theme/_index.md
- ja/python-net/developer-guide/presentation-slide/remove-slide-from-presentation/_index.md
Updated the titles, keywords, and descriptions in the metadata for the articles: 
- Verwalten von Hoch- und Tiefstellung in Python
- Open a Presentation in Python
- Add Math Equations to PowerPoint Presentations in Python
- Apply or Change a Slide Layout in Python
- Python で PowerPoint テキスト段落を管理する
- Python で PowerPoint プレゼンテーションのテーマを管理する
- Python で PowerPoint プレゼンテーションからスライドを削除する
> SLIDESDOC-582 Improve article headers to increase CTR (batch 2)

- en/androidjava/getting-started/licensing/_index.md
- en/cpp/getting-started/licensing/_index.md
- en/java/getting-started/licensing/_index.md
- en/net/getting-started/licensing/_index.md
- en/nodejs-java/getting-started/licensing/_index.md
- en/nodejs-net/getting-started/licensing/_index.md
- en/php-java/getting-started/licensing/_index.md
- en/python-java/getting-started/licensing/_index.md
- en/python-net/getting-started/licensing/_index.md
Added a note about using new licenses with old versions of Aspose.Slides.
> SLIDESDOC-580 Add information about using new licenses with old versions of Aspose.Slides

- en/python-net/developer-guide/3d-presentation/_index.md
- en/python-net/developer-guide/modern-api/_index.md
- en/python-net/developer-guide/presentation-content/manage-hyperlinks/_index.md
- en/python-net/developer-guide/presentation-content/manage-text/manage-textbox/_index.md
- en/python-net/developer-guide/presentation-design/powerpoint-fonts/embedded-font/_index.md
- en/python-net/developer-guide/presentation-design/powerpoint-fonts/font-replacement/_index.md
- en/python-net/developer-guide/presentation-security/read-only-presentatiom/_index.md
- en/python-net/developer-guide/technical-articles/extracting-images-from-presentation-shapes/_index.md
- ja/python-net/developer-guide/presentation-content/manage-text/extract-text-from-presentation/_index.md
- ja/python-net/developer-guide/presentation-design/powerpoint-fonts/font-replacement/_index.md
- ja/python-net/developer-guide/presentation-security/read-only-presentatiom/_index.md
- ja/python-net/developer-guide/technical-articles/extracting-images-from-presentation-shapes/_index.md
- zh/python-net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-to-markdown/_index.md
- zh/python-net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-ppt-to-pptx/_index.md
Updated the titles, keywords, and descriptions for the articles:
- Create 3D Presentations in Python
- Enhance Image Processing with the Modern API
- Manage Hyperlinks in Presentations with Python
- Manage Text Boxes in Presentations with Python
- Embed Fonts in Presentations with Python
- Streamline Font Replacement in Presentations Using Python
- Save Presentations in Read-Only Mode Using Python
- Extract Images from Presentation Shapes in Python
- Python で PowerPoint プレゼンテーションから高度なテキスト抽出を行う
- Python でプレゼンテーションのフォント置換を効率化する
- Python でプレゼンテーションを読み取り専用モードで保存する
- Python でプレゼンテーションの図形から画像を抽出する
- 将演示文稿转换为 Markdown（Python)
- 将 PPT 转换为 PPTX（Python）
> SLIDESDOC-587 Improve article headers to increase CTR (batch 5)

- en/python-net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/ppt-vs-pptx/_index.md
- en/python-net/developer-guide/presentation-content/manage-blob/_index.md
- en/python-net/developer-guide/presentation-content/manage-text/manage-placeholder/_index.md
- en/python-net/developer-guide/presentation-content/powerpoint-charts/chart-types/bubble-chart/_index.md
- en/python-net/developer-guide/presentation-content/powerpoint-charts/chart-types/doughnut-chart/_index.md
- en/python-net/developer-guide/presentation-content/powerpoint-shapes/shape-animation/_index.md
- en/python-net/developer-guide/presentation-content/powerpoint-shapes/shape-types/rectangle/_index.md
- en/python-net/developer-guide/presentation-notes/_index.md
- en/python-net/developer-guide/presentation-security/watermark/_index.md
- en/python-net/developer-guide/technical-articles/multithreading/_index.md
- en/python-net/getting-started/features-overview/_index.md
- en/python-net/getting-started/metered-licensing/_index.md
- fr/python-net/developer-guide/presentation-content/manage-media-files/picture-frame/_index.md
- ja/python-net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/convert-powerpoint-to-video/_index.md
- ja/python-net/developer-guide/manage-presentation/create-presentation/_index.md
- ja/python-net/developer-guide/presentation-content/manage-blob/_index.md
- ja/python-net/developer-guide/presentation-content/manage-text/manage-autofit-settings/_index.md
- ja/python-net/developer-guide/presentation-content/manage-text/manage-placeholder/_index.md
- ja/python-net/developer-guide/presentation-content/powerpoint-shapes/shape-types/group/_index.md
- ja/python-net/developer-guide/presentation-content/powerpoint-table/manage-rows-and-columns/_index.md
- ja/python-net/developer-guide/presentation-design/powerpoint-fonts/custom-font/_index.md
- ja/python-net/developer-guide/presentation-design/presentation-background/_index.md
- ja/python-net/getting-started/features-overview/_index.md
- ru/python-net/developer-guide/presentation-security/digital-signature-in-powerpoint/_index.md
- zh/python-net/developer-guide/presentation-content/manage-text/manage-bullet-and-numbered-lists/_index.md
- zh/python-net/developer-guide/presentation-content/powerpoint-shapes/shape-animation/_index.md
- zh/python-net/developer-guide/presentation-content/powerpoint-smartart/manage-smartart/_index.md
- zh/python-net/getting-started/licensing/_index.md
Updated the titles, keywords, and descriptions for the articles:
- Understanding the Difference: PPT vs PPTX
- Manage BLOBs in Presentations with Python for Efficient Memory Use
- Manage Placeholders in Presentations with Python
- Customize Bubble Charts in Presentations with Python
- Customize Doughnut Charts in Presentations with Python
- Apply Shape Animations in Presentations with Python
- Add Rectangles to Presentations in Python
- Manage Presentation Notes in Python
- Add Watermarks to Presentations in Python
- Multithreading in Aspose.Slides for Python
- Features Overview
- Metered Licensing
- Ajouter des cadres photo aux présentations avec Python
- Python でプレゼンテーションをビデオに変換する
- Python でプレゼンテーションを作成する
- Python でプレゼンテーションの BLOB を管理してメモリを効率的に使用する
- Python で AutoFit を活用してプレゼンテーションを強化する …
> SLIDESDOC-592 Improve article headers to increase CTR (batch 9)

- en/net/getting-started/system-requirements/_index.md
Added information about supporting Linux systems to the article "System Requirements" (.NET). 
Added keywords and description for the article.
Added information about supported Windows systems, .NET versions, and Visual Studio versions.
> SLIDESDOC-579 Add information about supporting Linux Alpine

- en/java/developer-guide/technical-articles/updating-ole-objects-automatically-using-ms-powerpoint-add-in/_index.md
- en/net/developer-guide/technical-articles/updating-ole-objects-automatically-using-ms-powerpoint-add-in/_index.md
Updated the title, section title, text, and code example. 
Added keywords and description.
> SLIDESDOC-610 Update the article "Updating OLE objects automatically using MS PowerPoint Add In"

- en/cpp/developer-guide/technical-articles/working-solution-for-chart-resizing-in-pptx/_index.md
- en/java/developer-guide/technical-articles/working-solution-for-chart-resizing-in-pptx/_index.md
- en/net/developer-guide/technical-articles/working-solution-for-chart-resizing-in-pptx/_index.md
Updated the text and formatted the code examples (.NET, C++, Java). 
Added keywords and description.
> SLIDESDOC-612 Update the article "Working Solution for Chart Resizing in PPTX"

- en/cpp/developer-guide/technical-articles/applying-protection-to-presentation/_index.md
- en/java/developer-guide/technical-articles/applying-protection-to-presentation/_index.md
- en/net/developer-guide/technical-articles/applying-protection-to-presentation/_index.md
- en/python-net/developer-guide/technical-articles/applying-protection-to-presentation/_index.md
Updated the title, section titles, text, and code examples in the article (.NET, C++, Java, Python).
Added keywords, description, and links to API Reference.
> SLIDESDOC-613 Update the article "Applying Protection to Presentation"

- en/cpp/developer-guide/technical-articles/getting-warning-callbacks-for-fonts-substitution-in-aspose-slides/_index.md
- en/java/developer-guide/technical-articles/getting-warning-callbacks-for-fonts-substitution-in-aspose-slides/_index.md
- en/net/developer-guide/technical-articles/getting-warning-callbacks-for-fonts-substitution-in-aspose-slides/_index.md
- en/python-net/developer-guide/technical-articles/getting-warning-callbacks-for-fonts-substitution-in-aspose-slides/_index.md
Updated the title; added keywords and description for SEO. 
Updated the text and code examples (.NET, C++, Java).
Updated the text for Python version.
> SLIDESDOC-618 Update the article "Getting Warning Callbacks for Fonts Substitution in Aspose.Slides"

- en/python-net/developer-guide/manage-presentation/open-presentation/_index.md
- en/python-net/developer-guide/presentation-content/manage-text/manage-paragraph/_index.md
Updated the text and code examples in 2 articles.
> SLIDESDOC-628 Update articles to improve time to read (batch 2)

- en/python-net/developer-guide/manage-presentation/import-presentation/_index.md
- en/python-net/developer-guide/manage-presentation/merge-presentation/_index.md
- en/python-net/developer-guide/presentation-content/manage-hyperlinks/_index.md
- en/python-net/developer-guide/presentation-content/powerpoint-shapes/shape-types/group/_index.md
- en/python-net/developer-guide/presentation-content/powerpoint-table/manage-table/_index.md
- en/python-net/developer-guide/presentation-design/presentation-header-and-footer/_index.md
- en/python-net/developer-guide/presentation-slide/add-slide-to-presentation/_index.md
- en/python-net/developer-guide/presentation-slide/slide-section/_index.md
> SLIDESDOC-648 Update articles to improve time to read (batch 5)

- en/androidjava/ai/_index.md
- en/androidjava/ai/translator/_index.md
- en/java/ai/_index.md
- en/java/ai/generator/_index.md
- en/java/ai/translator/_index.md
- en/net/ai/_index.md
- en/net/ai/generator/_index.md
- en/net/ai/translator/_index.md
- en/nodejs-java/ai/_index.md
- en/nodejs-java/ai/generator/_index.md
- en/nodejs-java/ai/translator/_index.md
- en/php-java/ai/_index.md
- en/php-java/ai/translator/_index.md
- en/python-net/ai/_index.md
- en/python-net/ai/generator/_index.md
- en/python-net/ai/translator/_index.md
Added keywords and descriptions to the .NET articles:
- AI Features in Aspose.Slides
- AI-Powered Multilingual Slide Generator
- AI-Powered Presentation Translator
Fixed the link to the article "AI-Powered Presentation Translator". 
Formatted the articles. 
Added the articles for Aspose.Slides for Java, Android via Java, Node.js via Java, PHP via Java, and Python via .NET according to the .NET version.
> SLIDESDOC-636 Add articles about AI for other platforms
